# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kvstore_pb2 as kvstore__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kvstore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetData = channel.unary_unary(
                '/kvstore.KVStore/SetData',
                request_serializer=kvstore__pb2.GrpcDataRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GrpcStatusResponse.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/kvstore.KVStore/GetData',
                request_serializer=kvstore__pb2.GrpcKeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GrpcDataResponse.FromString,
                _registered_method=True)
        self.DeleteData = channel.unary_unary(
                '/kvstore.KVStore/DeleteData',
                request_serializer=kvstore__pb2.GrpcKeyRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GrpcStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kvstore.KVStore/HealthCheck',
                request_serializer=kvstore__pb2.GrpcHealthCheckRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GrpcHealthCheckResponse.FromString,
                _registered_method=True)


class KVStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetData,
                    request_deserializer=kvstore__pb2.GrpcDataRequest.FromString,
                    response_serializer=kvstore__pb2.GrpcStatusResponse.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=kvstore__pb2.GrpcKeyRequest.FromString,
                    response_serializer=kvstore__pb2.GrpcDataResponse.SerializeToString,
            ),
            'DeleteData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteData,
                    request_deserializer=kvstore__pb2.GrpcKeyRequest.FromString,
                    response_serializer=kvstore__pb2.GrpcStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=kvstore__pb2.GrpcHealthCheckRequest.FromString,
                    response_serializer=kvstore__pb2.GrpcHealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.KVStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kvstore.KVStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStore/SetData',
            kvstore__pb2.GrpcDataRequest.SerializeToString,
            kvstore__pb2.GrpcStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStore/GetData',
            kvstore__pb2.GrpcKeyRequest.SerializeToString,
            kvstore__pb2.GrpcDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStore/DeleteData',
            kvstore__pb2.GrpcKeyRequest.SerializeToString,
            kvstore__pb2.GrpcStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kvstore.KVStore/HealthCheck',
            kvstore__pb2.GrpcHealthCheckRequest.SerializeToString,
            kvstore__pb2.GrpcHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
