# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x07kvstore\"*\n\x08GrpcData\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\"?\n\x0fGrpcDataRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x11.kvstore.GrpcData\"\x1d\n\x0eGrpcKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x18\n\x16GrpcHealthCheckRequest\"U\n\x10GrpcDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x11.kvstore.GrpcData\"6\n\x12GrpcStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x17GrpcHealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xa0\x02\n\x07KVStore\x12@\n\x07SetData\x12\x18.kvstore.GrpcDataRequest\x1a\x1b.kvstore.GrpcStatusResponse\x12=\n\x07GetData\x12\x17.kvstore.GrpcKeyRequest\x1a\x19.kvstore.GrpcDataResponse\x12\x42\n\nDeleteData\x12\x17.kvstore.GrpcKeyRequest\x1a\x1b.kvstore.GrpcStatusResponse\x12P\n\x0bHealthCheck\x12\x1f.kvstore.GrpcHealthCheckRequest\x1a .kvstore.GrpcHealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRPCDATA']._serialized_start=26
  _globals['_GRPCDATA']._serialized_end=68
  _globals['_GRPCDATAREQUEST']._serialized_start=70
  _globals['_GRPCDATAREQUEST']._serialized_end=133
  _globals['_GRPCKEYREQUEST']._serialized_start=135
  _globals['_GRPCKEYREQUEST']._serialized_end=164
  _globals['_GRPCHEALTHCHECKREQUEST']._serialized_start=166
  _globals['_GRPCHEALTHCHECKREQUEST']._serialized_end=190
  _globals['_GRPCDATARESPONSE']._serialized_start=192
  _globals['_GRPCDATARESPONSE']._serialized_end=277
  _globals['_GRPCSTATUSRESPONSE']._serialized_start=279
  _globals['_GRPCSTATUSRESPONSE']._serialized_end=333
  _globals['_GRPCHEALTHCHECKRESPONSE']._serialized_start=335
  _globals['_GRPCHEALTHCHECKRESPONSE']._serialized_end=376
  _globals['_KVSTORE']._serialized_start=379
  _globals['_KVSTORE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
